extraction:
  cpp:
    after_prepare: 
      - python report.py 38
  cobol:
    after_prepare: 
      - python report.py 38
  csharp:
    after_prepare: 
      - python report.py 38
  java:
    after_prepare: 
      - python report.py 38
  javascript:
    after_prepare: 
      - python report.py 38
  python:
    after_prepare: 
      - python report.py 38
